### PR TITLE
Laravel 11.x Compatibility

### PR DESCRIPTION
**Pull request by laravel-shift**
This is an automated pull request from [Shift](https://laravelshift.com) to update your package code and dependencies to be compatible with Laravel 11.x.

**Before merging**, you need to:

- Checkout the `l11-compatibility` branch
- Review **all** comments for additional changes
- Thoroughly test your package

If you do find an issue, please report it by commenting on this PR to help improve future automation.

### CODE REVIEW

**Comment by laravel-shift** [comment]
:warning: The latest version of Laravel has a dependency for `phpunit/phpunit` of `^10.5`. If you would like to also upgrade your tests, you may run the [PHPUnit 10 Shift](https://laravelshift.com/upgrade-phpunit-10) for free.

**Comment by laravel-shift** [comment]
:warning: Shift detected GitHub Actions which run jobs using a version `matrix`. Shift attempted to [update your configuration](https://github.com/lorisleiva/laravel-search-string/pull/48/commits/c02ba67e1496e6da1f3483292276995e430c32e1?w=1) for Laravel 11. However, you should review these changes to ensure the desired combination of versions are built for your package.

**Comment by laravel-shift** [comment]
:alembic: **Using this package?** If you would like to help test these changes or believe them to be compatible, you may update your project to reference this branch.

To do so, temporarily add Shift's fork to the `repositories` property of your `composer.json`:

```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/laravel-shift/laravel-search-string.git"
        }
    ]
}
```

Then update your dependency constraint to reference this branch:

```json
{
    "require": {
        "lorisleiva/laravel-search-string": "dev-l11-compatibility",
    }
}
```

Finally, run: `composer update`

**Comment by mbardelmeijer** [comment]
@lorisleiva would you mind taking a look at this PR to add Laravel 11 support? Thanks! 🙏

**Comment by lorisleiva** [comment]
Hi there, I'm afraid this is a lot more problematic than anticipated. The HOA compiler that this uses has been abandoned for a while now and while it worked brilliantly all these years, new PHP syntax seem to have made that package unusable.

Changing the compiler would be a huge undertaking that I'm not willing to tackle at this point so, unless someone is able to save this package by submitting a PR that swaps the compiler for another implementation, this package will stay as-is for the foreseeable future.

**Comment by jorbascrumps** [comment]
@lorisleiva Would you accept a PR with this fork? https://github.com/hiqdev/hoa-compiler

**Comment by lorisleiva** [comment]
Yeah that'd be great! I'm assuming that's the exact same compiler but with the latest PHP versions?

**Comment by jszobody** [comment]
@lorisleiva Is this `laravel-search-string` package effectively dead at this point? We've been looking all over for something like this, thrilled to find it, only to realize it doesn't work with L11. Do you expect to move to a hoa/compiler fork anytime soon and bring this package up to full L11 compatibility?

**Pull request closed without merging**
